# Generated by Django 6.0.2 on 2026-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cat_name',
            new_name='pet_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pet_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
