"""
Django settings for petbook project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import sentry_sdk


# Načtení environmentálních proměnných z .env souboru
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Místo natvrdo zapsaného klíče se načte z .env
SECRET_KEY = os.environ.get('SECRET_KEY')

# Bude True jen tehdy, když je to v .env takto explicitně napsáno
DEBUG = os.environ.get('DEBUG') == 'True'

# Povolíme lokální vývoj i produkční doménu na Fly.io
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'petbook.fly.dev']

# DEVOPS PROAKTIVNÍ KROK: 
# Protože Fly.io nasazuje automaticky HTTPS, Django formuláře (jako login) 
# by bez tohoto nastavení vyhodily chybu "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = ['https://petbook.fly.dev']
# TÍMTO ŘÍKÁME DJANGU: "Pokud ti Fly.io (proxy) pošle hlavičku X-Forwarded-Proto, věř mu, že je to HTTPS!"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'cloudinary_storage',
    'cloudinary',

    # Local apps
    'tweets',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # PŘIDÁNO: Zde říkáme Djangu, aby hledal šablony v hlavní složce 'templates'
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'petbook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Pokud je DATABASE_URL v .env, použije Supabase, jinak spadne zpět na lokální SQLite (bezpečný fallback)
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600, # Udržuje spojení chvíli otevřené pro lepší výkon (connection pooling)
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# TOTO JE KLÍČ PRO PRODUKCI (Zajistí, že se posbírá i CSS od Admina)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Použití WhiteNoise pro extrémně rychlé servírování statických souborů v produkci
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Původní MEDIA_URL zůstává,  MEDIA_URL = '/media/'

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Tvé nové rozkouskované nastavení
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    'UPLOAD_PRESET': os.environ.get('CLOUDINARY_UPLOAD_PRESET'), # Doporučuji přidat i toto
    'MAGIC_ALIASES': {
        'post_images': 'f_webp,q_auto,c_limit,w_1920',
        'avatars': 'f_webp,q_auto,c_fill,w_400,h_400' # Avatary rovnou ořízneme na čtverec
    }
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Nastavení pro produkční prostředí (aktivuje se jen když vypneš DEBUG)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Definice našeho vlastního uživatelského modelu (Aplikace.Model)
AUTH_USER_MODEL = 'users.CustomUser'

# DSN načteme bezpečně z .env (na GitHubu z GitHub Secrets)
SENTRY_DSN = os.environ.get('SENTRY_DSN')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Sledujeme 100% chyb a 20% výkonnostních metrik (Performance Monitoring)
        traces_sample_rate=0.2,
        profiles_sample_rate=0.2,
    )

# Vlastní přihlašování (Username NEBO E-mail)
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CELERY & REDIS NASTAVENÍ
# Lokálně použije 'redis://localhost:6379/0', v produkci vezme REDIS_URL z .env
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ODESÍLÁNÍ E-MAILŮ (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'

# Tyto dvě hodnoty pošleme do Fly.io přes secrets
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')